# This file was generated by GoReleaser. DO NOT EDIT.
cask "builder" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "9cd35f0ff6ecce2598d509e67252ce43b6619ea31a08d2ea9f4e5aa850fd654d"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/client_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3393f07ef1018d5df4b3596e7c1325f1561b599b6dbd7043e7f563093a38d856"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/client_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "262cf7f2c27ebd5b0abc21b6cfe91471ee6a80ac9cb1b12e7632373e570ea72f"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/client_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6640ba65e968c5ab4e172e51492792a18d78919ccf7825fc6871aaef684f13f5"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/client_#{version}_linux_arm64.tar.gz"
    end
  end

  name "builder"
  desc "A teeny-tiny tool to build stuff"
  homepage "https://github.com/zeiss/builder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"] if OS.mac?
  end

  # No zap stanza required

end
