# This file was generated by GoReleaser. DO NOT EDIT.
cask "builder" do
  version "0.2.1"

  on_linux do
    on_intel do
      sha256 "087b28f3378b43532e51977985ccb14ac014345acd426873fd3d0d159cd86719"
      url "https://github.com/ZEISS/builder/releases/download/v#{version}/client_#{version}_linux_amd64.tar.gz",
        verified: "github.com/zeiss/builder"
    end
    on_arm do
      sha256 "f6b325ee8d7ab63c1ceb62d28a02b271b46db65a5c1b0706385940525193a9b2"
      url "https://github.com/ZEISS/builder/releases/download/v#{version}/client_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zeiss/builder"
    end
  end

  name "builder"
  desc "A teeny-tiny tool to build stuff"
  homepage "https://github.com/zeiss/builder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"] if OS.mac?
  end

  # No zap stanza required

end
