# This file was generated by GoReleaser. DO NOT EDIT.
cask "builder" do
  version "0.3.15"

  on_macos do
    on_intel do
      sha256 "e06b5053edbe09e7c65d6ae353856c965f0f6bdf6fcd82b0cd388277045088e2"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/builder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1736ef703fd3fb78e558436722273e646b6eb44183e624cdd589314bed94ffe"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/builder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16bb5a7a743e8eb50bdc3befd47e400ea83464dd8c44dcffa2ad1db27d71bd76"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/builder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3ceb483968e7d6a6cdc3d4aae5d7ccf24dc43b124418c397e939c8a4ff5dfcd"
      url "https://github.com/zeiss/builder/releases/download/v#{version}/builder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "builder"
  desc "A teeny-tiny tool to build stuff"
  homepage "https://github.com/zeiss/builder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "builder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/builder"] if OS.mac?
  end

  # No zap stanza required

end
